# Generated by Django 5.1.1 on 2024-10-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radmin',
            old_name='decsription',
            new_name='description',
        ),
    ]
