# Generated by Django 5.1.1 on 2024-10-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radmin', '0002_rename_decsription_radmin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radmin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='up_media/'),
        ),
    ]
